default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: postgres

development:
  <<: *default
  database: <%= Rails.application.name.underscore %>_development

test:
  <<: *default
  database: <%= Rails.application.name.underscore %>_test

production:
  <<: *default
  database: <%= Rails.application.name.underscore %>_production
  username: <%= Rails.application.name.underscore %>
  password: <%= ENV["#{Rails.application.name.underscore.upcase}_DATABASE_PASSWORD"] %>
